version: "3.8"

services:
  web:
    build: ./
    ports:
      - "5000:5000"
    command: "uvicorn main:app --host 0.0.0.0 --port 5000"
    volumes:
      - ./:/app
    depends_on:
      - redis

  worker:
    build: ./
    command: celery -A services.celery worker --pool=solo --loglevel=info --concurrency=1
    volumes:
      - ./:/app
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:7379"
